### ISSUE TITLE
Crash on `get_software_versions`

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#106]
**Describe the bug**
When running the `dev` branch, the following error occurs:

```
Dec-13 21:16:39.933 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (127)

Command executed:

  echo 2.0.3 &> v_pipeline.txt
  echo 0.32.0 &> v_nextflow.txt
  fastqc --version &> v_fastqc.txt 2>&1 || true
  multiqc --version &> v_multiqc.txt 2>&1 || true
  bwa &> v_bwa.txt 2>&1 || true
  samtools --version &> v_samtools.txt 2>&1 || true
  AdapterRemoval -version  &> v_adapterremoval.txt 2>&1 || true
  picard MarkDuplicates --version &> v_markduplicates.txt  2>&1 || true
  dedup -v &> v_dedup.txt 2>&1 || true
  preseq &> v_preseq.txt 2>&1 || true
  gatk BaseRecalibrator --version 2>&1 | grep Version: > v_gatk.txt 2>&1 || true
  vcf2genome &> v_vcf2genome.txt 2>&1 || true
  fastp --version &> v_fastp.txt 2>&1 || true
  bam --version &> v_bamutil.txt 2>&1 || true
  qualimap --version &> v_qualimap.txt 2>&1 || true
  
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Command error:
  /bin/bash: line 0: cd: /projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/ABM006.A0101/work/f9/4d534ff781d3f9e2b0cd1f1822a23a: No such file or directory
  /bin/bash: .command.stub: No such file or directory

```

**To Reproduce**

The following command was used:

```
nextflow run nf-core/eager \
-profile standard,singularity \
--reads '/projects1/users/fellows/nextflow/eager2/dev_testing/data/ABM006.A0101/*_R{1,2}*fastq.gz' \
--pairedEnd \
--fasta '/projects1/users/fellows/nextflow/eager2/dev_testing/references/hg19_actual/hg19_complete.fasta' \
--outdir '/projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/ABM006.A0101' \
--name 'eager_nextflow_dev' \
--email fellows@shh.mpg.de \
--max_cpus 4 \
--max_mem 32G \
--skip_preseq \
--min_adap_overlap 1 \
--clip_readlength 30 \
--clip_min_read_quality 20 \
--bwaalnn 0.01 \
--bwalnl 32 \
--bam_discard_unmapped \
--bam_unmapped_type fastq \
--dedupper dedup \
--dedup_all_merged \
-r dev
```

With input data as paired end NextSeq data to the hg19 reference FASTA.

**Expected behavior**
To run through.

**Operating System:**
 - OS: Ubuntu 14.04

**Additional context**
[get_software_version-faulty_work_directory-f9.zip](https://github.com/nf-core/eager/files/2677591/get_software_version-faulty_work_directory-f9.zip)
[nextflow.log](https://github.com/nf-core/eager/files/2677592/nextflow.log)

**Comment by jfy133** [comment]
For reference, I also get a later error after the above, although I assume this is a separate issue:

```
Dec-14 20:25:40.155 [main] ERROR nextflow.script.WorkflowMetadata - Failed to invoke `workflow.onComplete` event handler
java.io.IOException: Cannot run program "mail": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at org.codehaus.groovy.runtime.ProcessGroovyMethods.execute(ProcessGroovyMethods.java:596)
        at org.codehaus.groovy.runtime.ProcessGroovyMethods.execute(ProcessGroovyMethods.java:663)
        at org.codehaus.groovy.runtime.dgm$932.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at _nf_script_9f6f15d7$_run_closure39.doCall(_nf_script_9f6f15d7:1120)
        at _nf_script_9f6f15d7$_run_closure39.doCall(_nf_script_9f6f15d7)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:421)
        at groovy.lang.Closure.call(Closure.java:415)
        at nextflow.script.WorkflowMetadata$_invokeOnComplete_closure4.doCall(WorkflowMetadata.groovy:373)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:421)
        at groovy.lang.Closure.call(Closure.java:437)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2295)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2280)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2321)
        at nextflow.script.WorkflowMetadata.invokeOnComplete(WorkflowMetadata.groovy:371)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1018)
 at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1001)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
        at nextflow.script.WorkflowMetadata$_closure3.doCall(WorkflowMetadata.groovy:237)
        at nextflow.script.WorkflowMetadata$_closure3.call(WorkflowMetadata.groovy)
        at nextflow.Session.shutdown0(Session.groovy:619)
        at nextflow.Session.destroy(Session.groovy:574)
        at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:387)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:170)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:235)
        at nextflow.cli.Launcher.run(Launcher.groovy:432)
        at nextflow.cli.Launcher.main(Launcher.groovy:590)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 57 common frames omitted

```

**Comment by apeltzer** [comment]
Problems identified together with @jfy133 

- Singularity Bind Path is not accessing the user directory correctly, need to be set by Administrator first, otherwise path in container != path outside container, thus the failure
- eMail has to be either configured by you [see here for details](https://www.nextflow.io/docs/latest/mail.html#basic-mail) and/or available on the node running the jobs

I asked IT to configure the path for you, so we can re-open if this is a problem again :-)
