### ISSUE TITLE
Unsupported class file major version 67

### ISSUE THREAD

**Issue by themudo** [nf-core/eager#1097]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug

I have just installed nextflow and nf-core/eager for a new user on a CentOS cluster. I have installed it previously on another user on the same machine one year ago, and it works perfectly. For this new user I am getting an error when running the test data, and can't figure out what is wrong. There is no file ` /home/user/.nextflow/scm`

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: ` NXF_VER=22.10.1 nextflow run nf-core/eager -profile test,singularity`
2. See error: 
```
$ NXF_VER=22.10.1 nextflow run nf-core/eager -profile test,singularity
 Nextflow 24.10.0 is available - Please consider updating your version to it
 N E X T F L O W  ~  version 22.10.1
 Project config file is malformed -- Cause: Compile failed for sources FixedSetSources[name='/groovy/script/ScriptF323DC9F16B890BB28C41C980C2754A6/_nf_config_bcebb1ca']. 
 Cause: BUG! exception in phase 'semantic analysis' in source unit '/groovy/script/ScriptF323DC9F16B890BB28C41C980C2754A6/_nf_config_bcebb1ca' Unsupported class file major version 67
```

## Expected behaviour

Test file should be downloaded and pipeline should execute without errors.

## Log files
Looking into the log file gives me a java error:

```
Oct-31 12:40:38.838 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/user/.nextflow/scm
Oct-31 12:40:40.281 [main] DEBUG nextflow.cli.Launcher - Operation aborted
ch.grengine.except.CompileException: Compile failed for sources FixedSetSources[name='/groovy/script/ScriptF323DC9F16B890BB28C41C980C2754A6/_nf_config_bcebb1ca']. Cause: BUG! exception in phase 'semantic analysis' in source unit '/groovy/script/ScriptF323DC9F16B890BB28C41C980C2754A6/_nf_config_bcebb1ca' Unsupported class file major version 67
        at ch.grengine.code.groovy.DefaultGroovyCompiler.compile(DefaultGroovyCompiler.java:278)
        at ch.grengine.load.DefaultTopCodeCache.getUpToDateCode(DefaultTopCodeCache.java:79)
        at ch.grengine.load.LayeredClassLoader.loadMainClass(LayeredClassLoader.java:179)
        at ch.grengine.engine.LayeredEngine.loadMainClass(LayeredEngine.java:199)
        at ch.grengine.Grengine.loadMainClass(Grengine.java:692)
        at ch.grengine.BaseGrengine.load(BaseGrengine.java:538)
        at ch.grengine.BaseGrengine.load(BaseGrengine.java:420)
        at ch.grengine.BaseGrengine$load.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at nextflow.config.ConfigParser.loadScript(ConfigParser.groovy:223)
        at nextflow.config.ConfigParser.parse(ConfigParser.groovy:274)
        at nextflow.scm.AssetManager.getManifest0(AssetManager.groovy:452)
        at nextflow.scm.AssetManager.memoizedMethodPriv$getManifest(AssetManager.groovy:435)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
        at nextflow.scm.AssetManager$_closure2.doCall(AssetManager.groovy)
        at nextflow.scm.AssetManager$_closure2.doCall(AssetManager.groovy)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
        at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.scm.AssetManager.getManifest(AssetManager.groovy)
        at nextflow.scm.AssetManager.getGitConfigRemoteUrl(AssetManager.groovy:1047)
        at nextflow.scm.AssetManager.getGitConfigRemoteDomain(AssetManager.groovy:1056)
        at nextflow.scm.AssetManager.guessHubProviderFromGitConfig(AssetManager.groovy:1079)
        at nextflow.scm.AssetManager.guessHubProviderFromGitConfig(AssetManager.groovy)
        at nextflow.scm.AssetManager.checkHubProvider(AssetManager.groovy:226)
        at nextflow.scm.AssetManager.build(AssetManager.groovy:129)
        at nextflow.scm.AssetManager.<init>(AssetManager.groovy:105)
        at nextflow.cli.CmdRun.getScriptFile0(CmdRun.groovy:503)
        at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:444)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:300)
        at nextflow.cli.Launcher.run(Launcher.groovy:487)
        at nextflow.cli.Launcher.main(Launcher.groovy:646)
Caused by: org.codehaus.groovy.GroovyBugError: BUG! exception in phase 'semantic analysis' in source unit '/groovy/script/ScriptF323DC9F16B890BB28C41C980C2754A6/_nf_
config_bcebb1ca' Unsupported class file major version 67
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:905)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
        at ch.grengine.code.groovy.DefaultGroovyCompiler.compile(DefaultGroovyCompiler.java:241)
        ... 50 common frames omitted
```
Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] The `.nextflow.log` file 
- [x] The exact error: 

## System

- Hardware: HPC
- Executor: local
- OS:  CentOS Linux
- Version 

## Nextflow Installation

- Version: 22.10.1

## Container engine

- Engine: Singularity
- version: 3.1.0-1.el7.centos
- Image tag:

**Comment by themudo** [comment]
Seems to have been a problem with java version. I had installed v.23 from Oracle directly, but then followed [these instructions](https://www.nextflow.io/docs/latest/install.html#installation) to install v17 from SDKMAN and now it works.
