### ISSUE TITLE
Failed to create conda enviroment

### ISSUE THREAD

**Issue by brenogomes50** [nf-core/eager#356]
**Describe the bug**
Hello, I've been trying to follow the Quick Start guide for nf-core/eager, and on step 4 which is to test the pipeline using test data, it's not working. 

**To Reproduce**
Steps to make me able to reproduce the behavior:
1. I run the following command line on my console:
 nextflow run nf-core/eager -profile conda,test --pairedEnd

**Expected behavior**
I don't know! Work?

**Screenshots**
![sc-1](https://user-images.githubusercontent.com/24258872/74867768-0675a700-5334-11ea-8b86-e44f398162bb.jpg)
![sc-2](https://user-images.githubusercontent.com/24258872/74867774-07a6d400-5334-11ea-911f-cdb85d3e8886.jpg)

**Operating System:**
 - OS: Windows 10 with WSL 

**Additional context**
Please provide me with the following files:
https://drive.google.com/drive/folders/10Hc6mrjMNv9udbzP-AXRDv4zSup0MXo0?usp=sharing
- `.nextflow.log` - on Google Drive
- `results/pipeline_info/...` - on Google Drive

**Comment by maxibor** [comment]
Can you try to see if you can install the conda environment (https://github.com/nf-core/eager/blob/master/environment.yml and then `conda env create -f environment.yml` ) in the WSL ?
I do not have a Windows machine to test, but I know that conda and the WSL are not a 100% match.

**Comment by jfy133** [comment]
Hi @brenogomes50 

Thanks for trying out EAGER and sending us your logs!

In addition to what @maxibor says, this could be a java/groovy issue (the what nextflow is based on). When I look at your log file, I see the following errors:

1) nextflow cannot download the testdata file(s) e.g.

```
Feb-19 13:52:25.121 [Actor Thread 19] DEBUG nextflow.util.CacheHelper - Unable to get file attributes file: https://github.com/nf-core/test-datasets/raw/eager2/testdata/Mammoth/JK2785_TGGCCGATCAACGA_L008_R1_001.fastq.gz.tengrand.fq.gz -- Cause: javax.net.ssl.SSLException: No PSK available. Unable to resume.
Feb-19 13:52:25.660 [Actor Thread 21] DEBUG n.util.BlockingThreadExecutorFactory - Thread pool name=FileTransfer; maxThreads=12; maxQueueSize=36; keepAlive=1m
Feb-19 13:52:25.910 [FileTransfer-thread-1] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://raw.githubusercontent.com/nf-core/test-datasets/eager2/reference/Mammoth_MT_Krause.fasta at /home/brenogomes50/work/stage/03/065be446e2d763a117d36c885f46ae/Mammoth_MT_Krause.fasta
```

and 2) can't donwnload conda environment

```
java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda env create --prefix /home/brenogomes50/work/conda/nf-core-eager-2.0.7-ae703f51b4468cabafc936bf43098f65 --file /home/brenogomes50/.nextflow/assets/nf-core/eager/environment.yml
  status : 120
  message:

	at nextflow.conda.CondaCache.getCachePathFor(CondaCache.groovy:333)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.processor.TaskRun.memoizedMethodPriv$getCondaEnv(TaskRun.groovy:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
	at nextflow.processor.TaskRun$_closure2.doCall(TaskRun.groovy)
	at nextflow.processor.TaskRun$_closure2.doCall(TaskRun.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction$1.provide(Memoize.java:139)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:123)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:399)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at nextflow.processor.TaskRun.getCondaEnv(TaskRun.groovy)
	at nextflow.processor.TaskRun$getCondaEnv$4.call(Unknown Source)
	at nextflow.processor.TaskProcessor.createTaskHashKey(TaskProcessor.groovy:1943)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:570)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:58)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I can see from similar errors for 1) via google, that there was a [bug in openJDK](https://github.com/eclipse/jetty.project/issues/2939) but I don't know if you're using that version of Java. But you can check to see if you have the latest version of Java.

Like @maxibor said - WSL is still somewhat experimental, so there could be issues there. We will ask around the rest of the nf-core community if anyone has experience in that area.

Finally, once conda is working, I would highly recommend trying out the `nextflow run nf-core/eager -r dev` branch as it has lots of improvements over 2.0.7.

**Comment by brenogomes50** [comment]
> Can you try to see if you can install the conda environment (https://github.com/nf-core/eager/blob/master/environment.yml and then `conda env create -f environment.yml` ) in the WSL ?
> I do not have a Windows machine to test, but I know that conda and the WSL are not a 100% match.

Well, @maxibor I did what you asked and the problem doesn't seem to be past us.
![sec3](https://user-images.githubusercontent.com/24258872/74937964-e7c2ef00-53cb-11ea-8f4e-0fe0437f1c46.jpg)
![sec4](https://user-images.githubusercontent.com/24258872/74937971-e98cb280-53cb-11ea-9019-b74272104555.jpg)

**Comment by jfy133** [comment]
@brenogomes50 I asked the wider nf-core community, and to be honest they all thought it would be very unlikely to get it working with WSL. They instead suggested to install a Virtual Machine tool like VirtualBox, install e.g. Ubuntu on there, and run nextflow pipelines with conda there instead. 

However, if you want to persist with WSL you could alternatively (and what is more recommended for nf-core), you could try installing docker or singularity on your WSL. This is better as docker/singularity is more stable than conda and you will have fully reproducible results. However again, there is no guaruntee it'll work on WSL.

Someone tried this a long time ago, but I don't know if they ever succecced: https://gitter.im/nextflow-io/nextflow/archives/2016/09/23

The virtual machine is our recommendation, basically.

**Comment by brenogomes50** [comment]
> @brenogomes50 I asked the wider nf-core community, and to be honest they all thought it would be very unlikely to get it working with WSL. They instead suggested to install a Virtual Machine tool like VirtualBox, install e.g. Ubuntu on there, and run nextflow pipelines with conda there instead.
> 
> However, if you want to persist with WSL you could alternatively (and what is more recommended for nf-core), you could try installing docker or singularity on your WSL. This is better as docker/singularity is more stable than conda and you will have fully reproducible results. However again, there is no guaruntee it'll work on WSL.
> 
> Someone tried this a long time ago, but I don't know if they ever succecced: https://gitter.im/nextflow-io/nextflow/archives/2016/09/23
> 
> The virtual machine is our recommendation, basically.

Thanks @jfy133 and @maxibor, I'll try Docker and if it won't work I'll just install Ubuntu.
