### ISSUE TITLE
Input FASTA check doesn't always work 

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#479]
From log
```
Jun-25 10:22:14.450 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: library_merge, genotyping_hc, output_documentation, nuclear_contamination, makeFastaIndex, convertBam, lanemerge_stripfastq, multivcfanalyzer, mtnucratio, genotyping_freebayes, makeSeqDict, genotyping_ug, makeBT2Index, bowtie2, adapter_removal, maltextract, bwa, malt, kraken, vcf2genome, samtools_flagstat, unzip_reference, sex_deterrmine, bedtools, damageprofiler, fastqc_after_clipping, circularmapper, preseq, genotyping_pileupcaller, kraken_parse, samtools_flagstat_after_filter, indexinputbam, bam_trim, samtools_filter, print_nuclear_contamination, get_software_versions, bwamem, additional_library_merge, circulargenerator, multiqc, fastp, endorSpy, qualimap, kraken_merge, decomp_kraken, lanemerge, dedup, pmdtools, fastqc, markDup, makeBWAIndex, strip_input_fastq
Jun-25 10:22:14.507 [PathVisitor-1] ERROR nextflow.Channel - /projects1/microbiome_foodtransforms/foodtransforms-samplescreening/03-preprocessing/Reference/GRCh38.fa
java.nio.file.NoSuchFileException: /projects1/microbiome_foodtransforms/foodtransforms-samplescreening/03-preprocessing/Reference/GRCh38.fa
        at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:975)
        at nextflow.file.PathVisitor.applyGlobPattern0(PathVisitor.groovy:120)
        at nextflow.file.PathVisitor.apply(PathVisitor.groovy:68)
        at nextflow.file.PathVisitor$_applyAsync_closure1.doCall(PathVisitor.groovy:77)
        at nextflow.file.PathVisitor$_applyAsync_closure1.call(PathVisitor.groovy)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

```

Command

```
nextflow run nf-core/eager -r dev \
-profile shh,sdag \
--input '../00-documentation.backup/01-nfcore-eager_prescreening_20200625.tsv' \
-name 'foodtransforms-screen-20200625' \
--email 'fellows@shh.mpg.de' \
-with-tower \
--fasta '../Reference/GRCh38.fa' \
--fasta_index '../Reference/GRCh38.fa.fai' \
--bwa_index '../Reference/GRCh38.fa' \
--seq_dict '../Reference/GRCh38.dict' \
--complexity_filter_poly_g \
--run_bam_filtering \
--bam_discard_unmapped \
--bam_unmapped_type 'fastq' \
--run_metagenomic_screening \
--metagenomic_tools 'malt' \
--database '../Reference/database/refseq-bac-arch-homo-2018_11' \
--malt_min_support_mode 'percent' \
--run_maltextract '../Reference/taxa_lists/core_genera-anthropoids_hominids_panhomo-20180131.txt' \
--maltextract_ncbifiles '../Reference/hops' \
--maltextract_destackingoff
```

**Comment by jfy133** [comment]
I can't replicate this currently.
