### ISSUE TITLE
Failed to invoke `workflow.onComplete` event handler

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#480]
When the pipeline crashes, most times I will get the following error (`-r 2.2.0dev`)

```
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Failed to invoke `workflow.onComplete` event handler

 -- Check script '/projects1/clusterhomes/fellows/.nextflow/assets/nf-core/eager/main.nf' at line: 2932 or see '.nextflow.log' file for more details
```

**Comment by jfy133** [comment]
I currently cannot replicate the error, so will leave open unless I come across a direct example.

**Comment by jfy133** [comment]
Found it again when there was an internal issue whe ntesting pileupcaller and trying to skip straight to genotyping with input bams, appears if no MultiQC report is created it will crash

Nextflow reports first line of which is the 'mail' version if statement here si the problematic

https://github.com/nf-core/eager/blob/ec5dd91011f94aeee4b3751724d3c853ad8c9b10/main.nf#L2992-L3007

It appears 'catch all' doesn't work

**Comment by jfy133** [comment]
I suspect because mqc_report is 'null'

```
 Jul-01 08:28:36.212 [main] ERROR nextflow.script.WorkflowMetadata - Failed to invoke `workflow.onComplete` event handler
294 java.lang.NullPointerException: Cannot invoke method size() on null object
295   at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
296   at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:43)
297   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
298   at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
299   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
300   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
301   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
302   at Script_1200f636$_runScript_closure152.doCall(Script_1200f636:2850)
```

**Comment by jfy133** [comment]
https://github.com/nf-core/eager/commit/33143b09ce99f5f0c2aee3a73ccc1fb30f1d15f9
