### ISSUE TITLE
CircularMapper silently fails because no FASTA is found

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#528]
It results in a BAM file but with 0 mapped reads. Test is CircularMapper test in .github/workflows/ci.yml

```
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... 0.20 sec
[bwa_aln_core] write to the disk... 0.00 sec
[bwa_aln_core] 9828 sequences have been processed.
[main] Version: 0.7.17-r1188
[main] CMD: bwa aln -t 2 -n 0.04 -l 1024 -k 2 -f JK2802.sai Mammoth_MT_Krause_500.fasta JK2802_AGAATAACCTACCA_L008_R1_001.fastq.gz.tengrand.fq_L2.se.truncated.gz
[main] Real time: 0.163 sec; CPU: 0.258 sec
[bwa_aln_core] convert to sequence coordinate... 0.01 sec
[bwa_aln_core] refine gapped alignments... 0.00 sec
[bwa_aln_core] print alignments... 0.02 sec
[bwa_aln_core] 9828 sequences have been processed.
[main] Version: 0.7.17-r1188
[main] CMD: bwa samse -r @RG\tID:ILLUMINA-JK2802\tSM:JK2802\tPL:illumina Mammoth_MT_Krause_500.fasta JK2802.sai JK2802_AGAATAACCTACCA_L008_R1_001.fastq.gz.tengrand.fq_L2.se.truncated.gz
[main] Real time: 0.075 sec; CPU: 0.073 sec
java.io.FileNotFoundException: /home/fellows/Documents/github/nf-core/eager/tests/output/work/20/0567c7ef19d2d045c7adcbe6159369/Mammoth_MT_Krause.fasta_500_elongated (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at RealignSAMFile.getChangedSequences(RealignSAMFile.java:99)
	at RealignSAMFile.<init>(RealignSAMFile.java:61)
	at RealignSAMFile.addCLIInterface(RealignSAMFile.java:413)
	at RealignSAMFile.main(RealignSAMFile.java:112)
DEBUG	2020-07-27 11:57:50	BlockCompressedOutputStream	Using deflater: Deflater
Number of overlapping reads: 0

Number of reads in regular genome: 0

Number of reads in elongation factor completely: 0

Number of reads in first n bases, where n is the length of the elongation: 0
```

**Comment by jfy133** [comment]
Fixed in https://github.com/nf-core/eager/commit/f6393fa156cc0c9e87a074eeba6b58b591969abe
