### ISSUE TITLE
Process exceeded running time limit (2h)

### ISSUE THREAD

**Issue by zhongxing123** [nf-core/eager#545]
hi
when I run my own ancient DNA analysis, I got the following error：
Error executing process > 'circularmapper (Test_R1)'

Caused by:
  Process exceeded running time limit (2h)
Could you give me some suggestions about this error
thanks
zhongxing

**Comment by jfy133** [comment]
Hi @zhongxing123 please check your first post here: https://github.com/nf-core/eager/issues/543 

I have already responded there for initial information that I need.

**Comment by zhongxing123** [comment]
hi @jfy133 , sorry for my late reply. My command was nohup nextflow run nf-core/eager -profile conda --reads '/home/xiangh/zhangx/data/mtwork/TS1C/TS1C_R{1,2}.fq.gz' --fasta '/home/xiangh/zhangx/data/mtwork/reference/bos_taurus/v00654.
fasta' --mapper circularmapper --bwaalnn 0.04 --bwaalnl 1024 --paired_end -r 2.1.0 and the .nextflow.log file was below.
[.nextflow.log.txt](https://github.com/nf-core/eager/files/5193199/default.nextflow.log.txt)


Please give me some suggestions about this error.
thanks

**Comment by jfy133** [comment]
Hi @zhongxing123, for this issue, in `.nextflow.log` I can see the following error near the end:

```
  [main] Real time: 1979.544 sec; CPU: 1973.580 sec
  java.io.FileNotFoundException: v00654.fasta_500_elongated (没有那个文件或目录)
  	at java.io.FileInputStream.open0(Native Method)
  	at java.io.FileInputStream.open(FileInputStream.java:195)
  	at java.io.FileInputStream.<init>(FileInputStream.java:138)
  	at java.io.FileReader.<init>(FileReader.java:72)
  	at RealignSAMFile.getChangedSequences(RealignSAMFile.java:99)
  	at RealignSAMFile.<init>(RealignSAMFile.java:61)
  	at RealignSAMFile.addCLIInterface(RealignSAMFile.java:413)
  	at RealignSAMFile.main(RealignSAMFile.java:112)
  DEBUG	2020-09-09 13:30:17	BlockCompressedOutputStream	Using deflater: Deflater
```
I guess for whatever reason this error caused the process to hang and not given an exit code to stop the pipeline (and then timed out).

If I remember correctly we found a bug in 2.1.0 which may be related. Version 2.2 (currently in `-r dev`) has a lot of structural changes and thus we have deferred a lot of  bug fixes to that version, including to circularmapper.

Please could you try with `-r dev` instead of 2.1.0, but please double check your input parameters as these may have changed (I _believe_ from your command above this is probably just changing `--reads` to `--input`, and removing `--paired_end` but not 100% sure)

**Comment by jfy133** [comment]
Hi @zhongxing123 do you have any updates for us?

**Comment by zhongxing123** [comment]
Hi, sorry for the late reply, I am a newbie in using eager2. Currently I can run it but I don't know how it works. However, when running to damageprofiler recently, it often appeared  as follows:
 Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
  	at java.util.Arrays.copyOf(Arrays.java:3181)
  	at java.util.ArrayList.grow(ArrayList.java:261)
  	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
  	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
  	at java.util.ArrayList.add(ArrayList.java:458)
  	at calculations.LengthDistribution.fillDistributionTable(LengthDistribution.java:61)
  	at calculations.DamageProfiler.processRecord(DamageProfiler.java:237)
  	at calculations.DamageProfiler.handleRecord(DamageProfiler.java:154)
  	at calculations.DamageProfiler.extractSAMRecords(DamageProfiler.java:111)
  	at calculations.StartCalculations.start(StartCalculations.java:298)
  	at RunDamageProfiler.main(RunDamageProfiler.java:37)
How can i solve this problem? Thank you very much for your letter. 
thanks
zhongxing123
发件人: James A. Fellows Yates
发送时间: 2020年9月25日 21:06
收件人: nf-core/eager
抄送: zhongxing123; Mention
主题: Re: [nf-core/eager] Process exceeded running time limit (2h) (#545)

Hi @zhongxing123 do you have any updates for us?

**Comment by jfy133** [comment]
Hi @zhongxing123 ,

Ok, looks like a different error now, and I assume as you are at the next step that the time limit issues is resolved. But I'm sorry, but that report is not so useful helpful for me to help you debug. Was that now with the `dev` version? 

Also, this is this related to your issue you posted here: https://github.com/nf-core/eager/issues/543? Or is that now resolved also using the `dev` version.

For each new thing you try, if you give me the command you use AND the file `.nextflow.log` (which should located be wherever you run the command) this would help a lot. Thanks!

**Comment by jfy133** [comment]
Closing this now as there has been no more information for over a month. Please feel free to open again if it is still a problem.

Note that you should try `-r 2.2.0` to see if that resolves your issues.
