### ISSUE TITLE
Unknown config attribute

### ISSUE THREAD

**Issue by barlavi1** [nf-core/eager#645]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug

After launching nextflow command the run is being terminated after several seconds with the following error 

**Unknown config attribute `params.genomes.GRCh37.projectDir` -- check config file: /mnt/data/barA/.nextflow/assets/nf-core/eager/nextflow.config**

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run nf-core/eager -r 2.2.2 -name TU_TEST -profile singularity -work-dir /mnt/data/barA/aDNA_TEST/WORK/ -params-file "/mnt/data/barA/aDNA_TEST/nf-params.json"

2. See error:  Unknown config attribute `params.genomes.GRCh37.projectDir` -- check config file: /mnt/data/barA/.nextflow/assets/nf-core/eager/nextflow.config

## Expected behaviour

Run without terminating 

## Log files
my params file is:
{
    "input": "/mnt/data/barA/aDNA_TEST/RAW/*/*.R{1,2}.fastq.gz",
    "fasta": "/mnt/data/barA/aDNA_TEST/SVEVO/Svevo.fasta",
    "bwa_index": "/mnt/data/barA/aDNA_TEST/SVEVO/BWA_INDEX/",
    "fasta_index": "/mnt/data/barA/aDNA_TEST/SVEVO/Svevo.fasta.fai",
    "large_ref": "true",
    "save_reference": "true",
    "outdir": "/mnt/data/barA/aDNA_TEST/RESULT/",
    "mapper": "bwamem",
    "hostremoval_mode": "",
    "dedup_all_merged": "true",
}

Have you provided the following extra information/files:

The next flow .log file:
Dec-28 09:18:44.182 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/eager -r 2.2.2 -name TU_TEST -profile singularity -work-dir /mnt/data/barA/aDNA_TEST/WORK/ -params-file /mnt/data/barA/aDNA_TEST/nf-params.json
Dec-28 09:18:44.275 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.07.0
Dec-28 09:18:44.409 [main] INFO  nextflow.cli.CmdRun - Pulling nf-core/eager ...
Dec-28 09:18:44.410 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nf-core/eager/contents/nextflow.config
Dec-28 09:18:46.515 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nf-core/eager/contents/main.nf
Dec-28 09:18:47.103 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nf-core/eager
Dec-28 09:18:47.317 [main] DEBUG nextflow.scm.AssetManager - Pulling nf-core/eager -- Using remote clone url: https://github.com/nf-core/eager.git
Dec-28 09:19:09.929 [main] INFO  nextflow.cli.CmdRun -  downloaded from https://github.com/nf-core/eager.git
Dec-28 09:19:10.396 [main] DEBUG nextflow.scm.AssetManager - Git config: /mnt/data/barA/.nextflow/assets/nf-core/eager/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/eager.git
Dec-28 09:19:10.396 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/eager` [TU_TEST] - revision: 85e2e3288a [2.2.2]
Dec-28 09:19:10.408 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /mnt/data/barA/.nextflow/assets/nf-core/eager/nextflow.config
Dec-28 09:19:10.409 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/data/barA/.nextflow/assets/nf-core/eager/nextflow.config
Dec-28 09:19:10.418 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Dec-28 09:19:11.908 [main] DEBUG nextflow.config.ConfigBuilder - In the following config object the attribute `params.genomes.GRCh37.projectDir` is empty:
  fasta=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa
  bwa=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/BWAIndex/genome.fa
  bowtie2=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/Bowtie2Index/
  star=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/STARIndex/
  bismark=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/BismarkIndex/
  gtf=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf
  bed12=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.bed
  readme=s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/README.txt
  mito_name='MT'
  macs_gsize='2.7e9'
  blacklist=[:]/assets/blacklists/GRCh37-blacklist.bed

Dec-28 09:19:11.914 [main] ERROR nextflow.cli.Launcher - Unknown config attribute `params.genomes.GRCh37.projectDir` -- check config file: /mnt/data/barA/.nextflow/assets/nf-core/eager/nextflow.config
nextflow.exception.ConfigParseException: Unknown config attribute `params.genomes.GRCh37.projectDir` -- check config file: /mnt/data/barA/.nextflow/assets/nf-core/eager/nextflow.config
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:400)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:179)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:402)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:179)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:63)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:402)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:402)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:627)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:640)
	at nextflow.script.ScriptRunner.<init>(ScriptRunner.groovy:88)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:228)
	at nextflow.cli.Launcher.run(Launcher.groovy:451)
	at nextflow.cli.Launcher.main(Launcher.groovy:633)

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag: 

## Additional context

I hope to solve this quickly.
thanks alot,
Bar

**Comment by barlavi1** [comment]
Bug fixed after using 
**export NXF_VER=20.05.0-edge**

**Comment by apeltzer** [comment]
The latest stable release of Nextflow is 20.10.0 - it's most likely a good idea to upgrade to that one once. There are no drawbacks :-)
