### ISSUE TITLE
FastQC can hang when insufficient memory

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#650]
Reported by @ashildv and replicated by me.

FastQC has a hard memory usage limit of 250MB, which can only be increased by adding more threads (with `-t`). As fastqc is written in java, it seems it doesn't 'die' when it gets a GC overhead limit error, and just keeps running forever

```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.io.BufferedReader.readLine(BufferedReader.java:356)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
```

I tested manually on the errored files by increasing threads to 2 and this then worked correctly.

Therefore the solution would be to switch fastqc from `sc_small` to `mc_small`.

**Comment by jfy133** [comment]
Solution applied in: https://github.com/nf-core/eager/pull/649/commits/bc0159f741ffd199ff670f201092b22157a0c31c
