### ISSUE TITLE
FASTQC single-end data process doesn't specify number of threads

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#879]
This means we can't increase memory based on the the number of threads, the way fastqc likes it.

Should be added for single-end, as well paired-end to help it cope with large data

**Comment by jfy133** [comment]
Repoted by @marcel-keller

**Comment by jfy133** [comment]
Note: if it runs out of memory it hangs on:

```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at uk.ac.babraham.FastQC.Utilities.QualityCount.<init>(QualityCount.java:33)
	at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:259)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:89)
	at java.lang.Thread.run(Thread.java:748)
	```
	
	And never dies
