### ISSUE TITLE
MultiQC error 

### ISSUE THREAD

**Issue by MinLuke** [nf-core/eager#983]
Hello everyone,
I am experiencing an issue using eager during the MultiQC step. This is the error message that I get:

```
Command executed:

  multiqc -f --title "f2323" --filename f2323_multiqc_report multiqc_config.yaml  .

Command exit status:
  1

Command output:
  (empty)

Command error:
  
    /// MultiQC 🔍 | v1.13
  
  |           multiqc | MultiQC Version v1.14 now available!
  |           multiqc | Report title: f2323
  |           multiqc | Only using modules: adapterRemoval, bowtie2, custom_content, damageprofiler, dedup, fastp, fastqc, gatk, kraken, malt, mtnucratio, multivcfanalyzer, picard, preseq, qualimap, samtools, sexdeterrmine, hops, bcftools
  Traceback (most recent call last):
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/bin/multiqc", line 10, in <module>
      sys.exit(run_multiqc())
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/multiqc/__main__.py", line 22, in run_multiqc
      multiqc.run_cli(prog_name="multiqc")
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/rich_click/rich_command.py", line 19, in main
      rv = super().main(*args, standalone_mode=False, **kwargs)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/multiqc/multiqc.py", line 286, in run_cli
      multiqc_run = run(**kwargs)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/multiqc/multiqc.py", line 612, in run
      template_mod = config.avail_templates[config.template].load()
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2464, in load
      self.require(*args, **kwargs)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2487, in require
      items = working_set.resolve(reqs, env, installer, extras=self.extras)
    File "/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages/pkg_resources/__init__.py", line 782, in resolve
      raise VersionConflict(dist, req).with_context(dependent_req)
  pkg_resources.ContextualVersionConflict: (Pygments 2.9.0 (/home/minluke/eager/work/conda/nf-core-eager-2.4.6-e279fa2e35f70a17452bc24c02c493f5/lib/python3.9/site-packages), Requirement.parse('pygments<3.0.0,>=2.14.0'), {'rich'})

Work dir:
  /home/minluke/eager/work/28/ab1dc8538745c61e6381a67ef279d2
```

I have installed nf-core eager 2.4.6 using the following environment.yml

```
name: nf-core-eager-2.4.6
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.4
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.2
  - conda-forge::pygments=2.9.0
  - bioconda::rename=1.601
  - conda-forge::openjdk=8.0.144 # Don't upgrade - required for GATK
  - bioconda::fastqc=0.11.9
  - bioconda::adapterremoval=2.3.2
  - bioconda::adapterremovalfixprefix=0.0.5
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.26.0
  - bioconda::samtools=1.12
  - bioconda::dedup=0.12.8
  - bioconda::angsd=0.935
  - bioconda::circularmapper=1.93.5
  - bioconda::gatk4=4.2.0.0
  - bioconda::gatk=3.5 ## Don't upgrade - required for MultiVCFAnalyzer
  - bioconda::qualimap=2.2.2d
  - bioconda::vcf2genome=0.91
  - bioconda::damageprofiler=0.4.9 # Don't upgrade - later versions don't allow java 8
  - bioconda::multiqc=1.13
  - bioconda::pmdtools=0.60
  - bioconda::bedtools=2.30.0
  - conda-forge::libiconv=1.16
  - conda-forge::pigz=2.6
  - bioconda::sequencetools=1.5.2
  - bioconda::preseq=3.1.2
  - bioconda::fastp=0.20.1
  - bioconda::bamutil=1.0.15
  - bioconda::mtnucratio=0.7
  - bioconda::pysam=0.16.0
  - bioconda::kraken2=2.1.2
  - conda-forge::pandas=1.2.4
  - bioconda::freebayes=1.3.5
  - bioconda::sexdeterrmine=1.1.2
  - bioconda::multivcfanalyzer=0.85.2
  - bioconda::hops=0.35
  - bioconda::malt=0.61
  - conda-forge::biopython=1.79
  - conda-forge::xopen=1.1.0
  - bioconda::bowtie2=2.4.4
  - bioconda::eigenstratdatabasetools=1.0.2
  - bioconda::mapdamage2=2.2.1
  - bioconda::bbmap=38.92
  - bioconda::bcftools=1.12
```

How can I resolve this problem? thanks you a lot

**Comment by jfy133** [comment]
Hi @MinLuke 

I can unfortunately replicate the error. I  find If I cahnge `pygments` to 2.14, then it works.

I'm going to make a patch to the pipeline now to fix this.

Cheers,

**Comment by jfy133** [comment]
@MinLuke please pull and try again with 2.4.7 :)

**Comment by MinLuke** [comment]
Thank you @jfy133  for you help. I have tried but I get the following message:
`Cannot find revision `2.4.7` -- Make sure that it exists in the remote repository `https://github.com/nf-core/eager``

**Comment by MinLuke** [comment]
Oh sure! thank you I forgot to pull it. Now it works thank you @jfy133 :)
